### ISSUE TITLE
free-writing以外のコードブロックが表示されてしまう。

### ISSUE THREAD

**Issue by hiramoto** [tadashi-aikawa/obsidian-free-writing#1]
素敵なプラグインありがとうございます！
便利に使えそうです。

1つお願いなのですが、free writing以外のコードブロックを表示しないようにできないでしょうか？今、Dataviewをページの中に埋め込んでおり、表示されてしまいます。
free-writingのバージョンは 0.9.0 です。
![Screenshot_20230715-180744](https://github.com/tadashi-aikawa/obsidian-free-writing/assets/4223173/4e9aefd4-335f-4722-a281-2b9ba986dd56)

**Comment by tadashi-aikawa** [comment]
@hiramoto 
ご報告ありがとうございます。こちらは実装漏れなので対応いたします 👍

**Comment by tadashi-aikawa** [comment]
@hiramoto 
[v0.9.1](https://github.com/tadashi-aikawa/obsidian-free-writing/releases/tag/0.9.1) で修正しました。ご確認ください。

**Comment by hiramoto** [comment]
ばっちり直ってました！
対応ありがとうございます。
これで快適に使えそうです。
