### ISSUE TITLE
記入欄のフォントが小さく感じる

### ISSUE THREAD

**Issue by hiramoto** [tadashi-aikawa/obsidian-free-writing#2]
先日は改善ありがとうございました。
大きめのフォントで使っているのですが、記入欄のフォントが小さく見づらく感じます。
もし記入欄のフォントサイズの設定がされているなら、それを外すことはできないでしょうか。

![image](https://github.com/tadashi-aikawa/obsidian-free-writing/assets/4223173/3b70fad7-3dbc-45ef-875d-7ab3f7f59ea5)

**Comment by tadashi-aikawa** [comment]
@hiramoto 
入力欄にはフォントサイズの設定をしていません。テーマのデフォルトスタイルが利用されているかと思います。

> 大きめのフォントで使っているのですが

これは具体的にどういうことでしょうか?  Obsidianのフォントサイズやズームサイズを変更してみましたが再現はしませんでした。

**Comment by hiramoto** [comment]
お返事ありがとうございます。
フォントサイズの設定をしてないとのことだったので、テーマのフォントを確認してみたところ、そちらのサイズが反映されていました。すみません。
私はズームサイズを変更して文字を大きくして使っているのですが、ズームサイズを変えても入力欄の文字のサイズが変わらなかったため、free-writingでフォントサイズの設定をしているのかと早合点してしまいました。

**Comment by tadashi-aikawa** [comment]
@hiramoto 
ご返信ありがとうございます。

私の環境(テーマ)でズームサイズを変更するとすべての文字が連動して変わりますので、お使いのスタイルを調整していただくのがいいかもです。

![image](https://github.com/tadashi-aikawa/obsidian-free-writing/assets/9500018/1e963811-1db7-4a5d-a597-f60724029253)

とはいえフォントサイズやズーム変更まで考慮したデザインにはなっていないため、こちらの造りが微妙であれば改善したいと思っております。

**Comment by hiramoto** [comment]
今のバージョンで使っていて特に不便を感じないのでイシューはクローズさせていただきます。
ご丁寧にお返事いただきありがとうございます。
